[package]
name = "sudoku"
version = "0.1.0"
authors = ["≈Åukasz Sitarski <lucassith@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3.5", features = ["full"] }
